#!/usr/bin/env python3
# TOKEN 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
# My password Benzene66


import ssl
import socket
import sys

def parse_cmd_line():
    try:
        url = sys.argv[0]
    except:
        sys.exit("Please provide proper URL")

def create_socket():
    try:
        s = socket.socket(socket.AF_INET, socket.IPPROTO_RAW)
    except socket.error as msg:
        sys.exit("Connection cannot be made" + msg)

def main():

    #parse the cmd line to get the url download link
    url = parse_cmd_line()

    # establish connection
    create_socket()



if __name__ == "__main__":
    main()