#!/usr/bin/env python3
# TOKEN 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
# My password Benzene66


import ssl
import socket
import sys

def parse_cmd_line():
    try:
        url = sys.argv[0]
    except:
        sys.exit("Please provide proper URL")


def main():

    url = parse_cmd_line()



if __name__ == "__main__":
    main()